const requiredData = [
    [
        {
            "attribute":1,
            "condition":"==",
            "value":12
        },
        {
            "attribute":2,
            "condition":"==",
            "value":10
        }
    ],
    [
        {
            "attribute":4,
            "condition":"=>",
            "value":1
        }
    ],
    [
        {
            "attribute":4,
            "condition":"=>",
            "value":1
        }
    ]
]